# Generated by Django 5.2.9 on 2025-12-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_business_unique_name_per_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.business'),
            preserve_default=False,
        ),
    ]
