# Generated by Django 4.2.11 on 2026-02-01 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocktransaction_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='business',
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product'),
        ),
    ]
