# Generated by Django 4.2.11 on 2026-02-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_stocktransaction_business_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='business',
            name='Unique name per business',
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='Unique name per business'),
        ),
    ]
